Interviewモデルの作成、面談日程の表示・登録・編集・削除機能の作成
KazumasaYasui/e-navigator pull request #2
Opened 2018-04-04 04:00 UTC by KazumasaYasui

やりたかったこと
---
- Interviewモデルの作成
- UserモデルとInterviewモデルのアソシエーション
- 面接日程の表示・登録
- 面接日程の編集・削除

やったこと
- Interviewモデルの作成
- UserモデルとInterviewモデルのアソシエーション
- 面接日程の表示・登録
- 面接日程の編集・削除

動作確認方法

- [1] ユーザーを新規で作成しログインする
- [2] トップページから自分の面接一覧ページへいく
- [3] 新規作成から面接日程を作成する
- [4] 作成後、詳細ページから一覧ページへいく
- [5] 一覧ページから編集ページへいき面接日程を更新する
- [6] 一覧ページに戻り、作成・更新した面接日程を削除する

2018-04-05 01:31 UTC, pokotyamu commented
見ます👀

2018-04-05 01:54 UTC, pokotyamu requested changes

2018-04-05 01:54 UTC, pokotyamu commented on app/models/interview.rb
> +  enum interview_status: { on_hold:0, approval:1, refusal:2 }
`on_hold` かぁ
他と合わせる意味で、一単語で揃える方が良さそう 👀 
`pending` とかどうでしょう？

2018-04-05 01:54 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> +end
ちょこちょこプログラムの最終行に改行が入ってないものがありますね。
エディターの設定で最終行の改行が保存時にかかるようにしておきましょう！
[なぜ最終行に改行が必要なのか - komagataのブログ](http://docs.komagata.org/5460)

2018-04-05 01:54 UTC, pokotyamu commented on app/models/user.rb
> +  has_many :interviews
has_many でリレーション作るの良いですね  👍 
ただ、このままだと、面接に紐づくユーザーが削除された時に、面接のレコードが残り続けてしまいます。

なんで、ユーザーが削除される時に、連動して面接も削除されるように実装してください！
やり方は調べてみて下さい 🙏

2018-04-05 01:54 UTC, pokotyamu commented on app/views/interviews/index.html.erb
> +    <% @interviews.each do |int| %>
ここでしか使わない変数名ですが、 `int` ってのはちょっと良くないですね。
Integer と間違えそうです。

特別長いわけではないので、不用意に変数名は略さないで、 interviews(複数)をループして１個ずつ取って処理するので、 interview(単数)で良いと思います 👍

2018-04-05 01:54 UTC, pokotyamu commented on config/application.rb
> +    config.time_zone = 'Asia/Tokyo'
time_zone の設定良いですね 👍

2018-04-05 01:58 UTC, pokotyamu commented
164b67f これは scaffold を使ってやりましたか？
前にも話した通り、若干コミット粒度が大きいかなと思いました。
戻りたくても、一気に変更が消えてしまいますよね？ 🤔 

コマンドを使ってファイルを生成したなら、そのコマンド名で１コミット。
リレーション作成で１コミット
みたいな感じで、結構コミットの粒度は細かく始めてみても良いかも知れません 🙏

2018-04-05 02:12 UTC, KazumasaYasui commented on app/models/interview.rb
> +  enum interview_status: { on_hold:0, approval:1, refusal:2 }
pendingいいですね、修正します！

2018-04-05 02:12 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> +    @interviews = Interview.all.order(created_at: :desc)
自分の面接って言いつつ、他のユーザーの一覧も持ってくるようになってるんですね 👀 
これは直したほうが良さそうに思います。

view で切り分けても良いのですが、ロジックは controller 側に実装するほうが良いと思います 👍

2018-04-06 05:08 UTC, pokotyamu commented
> 40afb25

細かいですが、改行の修正と、 enum キーの変更が混ざってますね 👀 
git reset コマンドを使えば、コミットのやり直しや、履歴をたどることが出来るので、調べてみて下さい。

今回の件では修正する必要はありません。

2018-04-06 05:18 UTC, pokotyamu approved these changes
問題なさそうです 🙆‍♂️

2018-04-06 05:18 UTC, pokotyamu commented on app/models/user.rb
> +  has_many :interviews, dependent: :destroy
紐付いているものを削除する指定いい感じですね 👍 

ちなみに↓のような書き方でも同じ挙動をすることができますが、違いはご存知ですか？

```
has_many :interviews, dependent: :delete_all
```

2018-04-06 05:18 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> +    @interviews = Interview.where(user_id: current_user.id).order(created_at: :desc)
user に関連をもたせている場合、

```
current_user.interviews.order(created_at: :desc)
```

こんな感じで指定することもできますね 👀 
知識として覚えておいてもいいかと思います！(修正の必要はないです)

2018-04-06 05:19 UTC, pokotyamu commented
> https://github.com/KazumasaYasui/e-navigator/pull/2#discussion_r179661867

ここで質問していますが、もし分からなければ調べてみて下さい 🙋‍♂️ 

作業自体はマージして次に進んでいただいて大丈夫です👍 👍

2018-04-09 01:11 UTC, merged