面接官が面談日程を承認・拒否するための機能
KazumasaYasui/e-navigator pull request #3
Opened 2018-04-11 06:44 UTC by KazumasaYasui

やりたかったこと
---
- 自分以外の全てのユーザーの一覧をトップページに表示する
- トップページに他の人の面接一覧ページへのリンクを追加する
- 面接官用の面接日程一覧ページを作成する
- 表示内容はパーシャルで出し分ける
- 面談日程を承認・拒否できるようにする

やったこと
----
- 自分以外の全てのユーザーの一覧をトップページに表示する
- トップページに他の人の面接一覧ページへのリンクを追加する
- 面接官用の面接日程一覧ページを作成する
- 表示内容はパーシャルで出し分ける
- 面談日程を承認・拒否できるようにする
このプルリクエストでやった内容を列挙しましょう。

動作確認方法
---
- [1] ユーザーを新規で作成する
- [2] ユーザーの面接日程を複数作成する
- [3] 一旦ログアウトし、別ユーザーを新規作成する
- [4] トップページから、[2]で作成したユーザーの面接一覧にいく
- [5] 任意の日程を選択し、面接日程が承認されたことを確認する
- [6] 面接一覧に戻り、別の日程でも承認されることを確認する

その他
---
1つの日程のみ承認状態にする良い方法がわからなかったので、
少し強引な方法になってしまいました。

2018-04-12 05:26 UTC, pokotyamu commented
見ます 🙋‍♂️

2018-04-12 05:44 UTC, pokotyamu requested changes
@KazumasaYasui 数点理解度チェック的な意味も込めた質問をしてます！
回答及び修正よろしくお願いします 🙏

2018-04-12 05:44 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> +    # binding.pry
binding.pry のコメント消し忘れてますよ 👮

2018-04-12 05:44 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> +    @current_user = User.find(current_user.id)
ここ、わざわざ current_user をインスタンス変数化している理由ってなんでしょうか？ 🤔

2018-04-12 05:44 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> +    # binding.pry
同じく binding.pry の消し忘れですね 👮

2018-04-12 05:44 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> +    @interviews = Interview.where(user_id: @user.id)
特定のユーザーに紐づく面接を全部取ってくる際、これでも良いんですが、以下のようにメソッドが生えているので、それを使いましょう 👍 

```
user.inteviews
```

2018-04-12 05:44 UTC, pokotyamu commented on app/views/interviews/index.html.erb
> +  <%= render partial: "other_interview" %>
partial は共通した view の部分パーツを呼び出すという意図で用意されているので、これは本来の意図とはちょっと違う気がしますね 🤔
新規作成ページと、編集ページのフォームの構成は同じでもいいですよね？
scaffold コマンドで作られるファイルとかを見てみると、どう使えばいいかが見えてくる気がします。

また、これぐらいの量なら同じファイル内で if 文分岐でも良さそうな気がします。

2018-04-12 05:44 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> +    @current_user_interviews = Interview.where(user_id: current_user.id).order(created_at: :desc)
ここも、 

```
current_user.inteviews
```

で同等の結果が得られるとおもいます。

2018-04-12 05:44 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> +    @current_user_interviews = Interview.where(user_id: current_user.id).order(created_at: :desc)
ちなみになんですが、なんで `created_at: :desc` しているんですか？
どんな意図でソートしているのかが気になって質問しています 😄

2018-04-12 05:44 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> +    @interviews.where(interview_status: "approval").update_all(interview_status: "refusal")
ここ、 update_all 使っていますが、

```
@interviews.where(interview_status: "approval").each do |interview|  
  interview.update(interview_status: "refusal") 
end 
```

との違いわかりますか？ 😄

2018-04-12 05:44 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> +    @interviews.where(interview_status: "approval").update_all(interview_status: "refusal")
ちなみに enum を使っているとヘルパーメソッドが生えるので、

```
@interviews.where(interview_status: "approval")
#=> approval な面接一覧
@interviews.approval
#=> approval な面接一覧
```

この２つが同じ結果を返す事ができます！
そのために enum を使っているみたいなところがあるので、積極的に使ってみましょう 😄

2018-04-12 05:44 UTC, pokotyamu commented on app/controllers/users_controller.rb
> +    # binding.pry
binding.pry (以下略

2018-04-12 05:47 UTC, pokotyamu commented
承認した人の面接一覧にいくのかと思ってしまったんですが、他の人の面接を承認した後の画面で一覧と押すと、自分の面接一覧に行くのは意図通りでしょうか？

2018-04-13 07:55 UTC, KazumasaYasui commented on app/controllers/interviews_controller.rb
> +    @current_user = User.find(current_user.id)
指摘されて考え直したら、全く必要なかったです！すみません😅

2018-04-13 08:12 UTC, KazumasaYasui commented on app/controllers/interviews_controller.rb
> +    @current_user_interviews = Interview.where(user_id: current_user.id).order(created_at: :desc)
```created_at: :desc```で最新の登録情報が上位にくるのかなのが良いかなと考えていたんですが、よく考えたら面接日程を昇順にさせたほうが良いと思いまして、```interview_datetime: :asc```に修正しました😅

2018-04-13 08:16 UTC, KazumasaYasui commented on app/views/interviews/index.html.erb
> +  <%= render partial: "other_interview" %>
なるほど！理解不足ですみません！修正します！

2018-04-13 08:21 UTC, KazumasaYasui commented on app/controllers/interviews_controller.rb
> +    @interviews.where(interview_status: "approval").update_all(interview_status: "refusal")
勉強になります！修正します！

2018-04-16 02:25 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> +    @current_user_interviews = Interview.where(user_id: current_user.id).order(created_at: :desc)
なるほどですね 👍 
わりとありがちなので、気をつけましょ 😄

2018-04-16 02:27 UTC, pokotyamu commented
> abdf411...2d06e50

コミット粒度めっちゃいい感じですね 👍

2018-04-16 02:42 UTC, pokotyamu commented
面接が決まっている状態で、同じ面接日のボタンを押すと、確定しますか？という内容の後、拒否状態へ更新されてしまうのですが、これは意図通りでしょうか？ 🤔 
![image](https://user-images.githubusercontent.com/3479317/38787778-1638b3e4-416b-11e8-91d5-a0f9fe1125c6.png)

↓↓↓

![image](https://user-images.githubusercontent.com/3479317/38787794-2c296220-416b-11e8-9820-ef6a15cd0fd8.png)

2018-04-16 02:42 UTC, pokotyamu requested changes
@KazumasaYasui ２点確認してほしい点があるので、よろしくお願いします 🙏

2018-04-16 02:42 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> +    @user = User.find(params[:user_id])
よく見たら、　
`@user = User.find(params[:user_id])` ここで、ユーザーをインスタンス変数にセットしているコードが複数箇所で出てますね 👀 

前準備的なコードは callback にまとめちゃいましょう！
また、DRY(Don't Repeat Yourself) なコードを目指しましょう！
ざっくり説明すると、DRY とは、複数箇所で同じ処理をしているコードを書かない(書いたとしても、メソッドで共通化する)ということで、 Rails の思想の中にも入っています。

参考
[1. Ruby on Railsとは | TECHSCORE(テックスコア)](http://www.techscore.com/tech/Ruby/Rails/quick-start/Rails1/)
[DRY原則をもう一度 -コンカレント・エンジニアリング- - Qiita](https://qiita.com/Koki_jp/items/d5f1b5f277b581888a1f)

2018-04-17 01:16 UTC, pokotyamu requested changes
１点指摘してます！

2018-04-17 01:16 UTC, pokotyamu commented on app/views/interviews/index.html.erb
> +  <% @interviews.where.not(interview_status: "approval").each do |interview| %>
View でロジック持っちゃうの良くないですね 👮 
View は、あくまで表示を担当するものなので、 Controller 側で渡す面接オブジェクトのリストを approval なものだけにしましょう。

2018-04-17 01:21 UTC, pokotyamu commented
> https://github.com/KazumasaYasui/e-navigator/pull/3#issuecomment-381464506

こちらで、意図通りか聞いている部分があるので、もし違うのでしたら、どうなっていてほしいかを教えてほしいです 🙏 
もし、同じボタンを押したら拒否状態になってもいいのだったら、メッセージ変えてくださいという指摘になりますよね？
それとか、ボタンは表示するけど押せなくするとかだとまた違う実装になります。

一方的にレビューを受けるだけでなく、会話しながらマージまで進めていきましょう 😄

2018-04-17 16:24 UTC, KazumasaYasui commented on app/views/interviews/index.html.erb
> +  <% @interviews.where.not(interview_status: "approval").each do |interview| %>
了解しました😅修正します！

2018-04-17 16:30 UTC, KazumasaYasui commented
承認された日程を選択できるようにする意図はなかったので、その日程は選択できないようにしようと思い、approvalを除外した日程をeachで回すようにしました！
もともとは選択でき尚且つ、ボタンを押すと承認状態が拒否状態になってしまっていましたが、それは自分の意図した動作ではなかったので修正しました😅

2018-04-18 01:46 UTC, pokotyamu commented
変数名の付け方とか、何をインスタンス変数にすべきかなど、気にすべき点は完走した後のフィードバック時に口頭で説明した方が良さそうなので、その時にお伝えしますね😄

2018-04-18 01:46 UTC, pokotyamu commented
動作確認しました 🙆‍♂️ 
良さそうなので、マージして次に進んでください 👍

2018-04-18 01:48 UTC, pokotyamu commented
![ukrrzmi](https://user-images.githubusercontent.com/3479317/38907243-e81110a6-42f5-11e8-9c61-2afc373e8931.gif)

2018-04-18 08:08 UTC, merged