面談日程を知らせるためのメール送信機能
KazumasaYasui/e-navigator pull request #4
Opened 2018-04-20 03:49 UTC by KazumasaYasui

やりたかったこと
---
- config/environmentsの開発環境と本番環境にメール設定を追加
- ユーザーが面接官を指定して面接日程を申請した際、指定した面接官に承認依頼メールが届くよう設定
- 指定された面接官が日程を確定した際、ユーザー、面接官双方に日程確定メールが届くよう設定
- Action MailerとGmailを利用する
- .envを用いて環境変数を利用し、Gmailの送信元Eメールと二段階認証パスワードを非公開にする

やったこと
----
- config/environmentsの開発環境と本番環境にメール設定を追加
- ユーザーが面接官を指定して面接日程を申請した際、指定した面接官に承認依頼メールが届くよう設定
- 指定された面接官が日程を確定した際、ユーザー、面接官双方に日程確定メールが届くよう設定
- Action MailerとGmailを利用する
- .envを用いて環境変数を利用し、Gmailの送信元Eメールと二段階認証パスワードを非公開にする

動作確認方法
---
- [1] ログインしたユーザーで、面接日程を複数作成し面接官に申請する
- [2] 面接官に日程承認依頼メールが届いているか確認する
- [3] 面接官が届いたメールのリンクから、ユーザーの日程承認依頼ページへ移動する
- [4] 適当な日程を承認し、ユーザーと面接官に日程確定メールが届いているか確認する

その他
---
本番環境ではherokuのconfigに環境変数を設定する必要があり、そこに引っかかってしまいました😅

2018-04-20 05:58 UTC, pokotyamu commented
コミットメッセージめっちゃ良いですね！
１コミット毎に見ていけば実装内容がわかったので、レビューしやすかったです 😄

2018-04-20 06:00 UTC, pokotyamu commented
dotenvをbundle という表現はちょっと 🤔 
「dotenv gem 」を追加とかなのかな

2018-04-20 06:41 UTC, pokotyamu requested changes
挙動としては申し分ないんだけど、命名とかで突っ込んでみました 👍  
反論も出来ると思うので、こう考えてみたいなのがあれば教えて下さい 🙏

2018-04-20 06:41 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> +    RequestMailer.send_when_request(interviewer, current_user).deliver
メソッド名に条件が含まれているのはあまりよろしくないですね 👮 
メソッドの中身を見ると、面接希望日が確定したことを知らせるメールを送るのが仕事ですよね？
なんで、 when といういつみたいな情報は不要で、 `#apply` みたいなメソッド名になるかと思います。

更に RequestMailer の request となってしまうと、ちょっと名前として被っている気もします。
Mailer の名前としては、何についてのメールなのか？というのが良いです。
例えば、ユーザーに関わることなら UserMailer だし、今回のように面接に関わることなら InterviewMailer かなと思います。

2018-04-20 06:41 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> +    RequestMailer.send_when_request(interviewer, current_user).deliver
考え方で言えば Controller の名前付けと似ている気がします↑

2018-04-20 06:41 UTC, pokotyamu commented on app/mailers/request_mailer.rb
> +         subject: '面接希望日が決まりました'
より良いコードという意味で、アドバイスすると、
このメソッドとしては、 current_user かどうかって知る必要ありますか？
どちらかと言うと、面接官と面接希望者というのが正しいですよね。

アプリケーションとしてここに来るのは current_user かもしれないんですが、 interviewer / interviewee という方が適切かなと思いました！
メソッド名の話しでもした通り、 user と書かずに、どんなユーザー？というのをコードに落とし込めるとより読みやすいコードになると思います！

2018-04-20 06:41 UTC, pokotyamu commented on app/mailers/request_mailer.rb
> +  default from: ENV['E_MAIL']
ここ送るメアドが一緒ならば継承元の ApplicationMailer に実装するほうがいいです。

2018-04-20 06:43 UTC, pokotyamu commented
> 本番環境ではherokuのconfigに環境変数を設定する必要があり、そこに引っかかってしまいました😅

これはあるあるですね！
ただ、一回やり方学ぶと、その後はそれを真似するだけなので、ぜひ覚えておいて下さい 👍

2018-04-20 07:35 UTC, KazumasaYasui commented on app/controllers/interviews_controller.rb
> +    RequestMailer.send_when_request(interviewer, current_user).deliver
自分としては```send_when_request```とか```send_when_complete```の方がわかりやすいかなと思ったんですが、Controllerの名前付けを意識してみると、```apply```とか```decide```の方が良いのかと納得しました😅
もともとRequestMailerとCompleteMailerの2つを使っていましたが、InterviewMailerに統一し、その中でapplyとdecideのメソッドを作成することにしました！

2018-04-20 07:45 UTC, KazumasaYasui commented on app/mailers/request_mailer.rb
> +         subject: '面接希望日が決まりました'
確かに仮引数をinterviewer/intervieweeにした方がわかりやすいと思いました！

2018-04-24 03:51 UTC, pokotyamu commented
うん！修正内容も問題なさそうに思います 👍 
LGTM です 🎉 
マージしちゃって大丈夫です 🙆

2018-04-24 05:05 UTC, merged